name: BUILD DOCKER IMAGE
on:
  push:
    branches:
        - master
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
            - run: docker build --tag pharogrammer/django-test:v0.1 .
            - run: docker login -u ${ secrets.DOCKER_USERNAME } -p ${ secrets.DOCKER_PASSWORD }
            - run: docker push pharogrammer/django-test:v0.1

